spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Seoul
    username: root
    password:
  jpa:
    database: mysql
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  type-aliases-package: com.study.springstudy2.dto
